version: "3.8"

services:
  # nginx:
  #   build:
  #     context: ./requirements/nginx
  #   image: nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "443:443"
  #   env_file:
  #     - .env
  # networks:
  #   - inception
  # depends_on:
  #   - wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    # networks:
    #   - inception

volumes:
  mariadb_data:

# networks:
#   inception:
#     drive: bridge